#!/usr/bin/env bash
[ -n "$E2E_SHIM_LOG" ] && echo "obsidian $*" >> "$E2E_SHIM_LOG"

case "$1" in
  unresolved|links|backlinks|orphans|deadends|properties|tags)
    exit 0
    ;;
  *)
    exit 0
    ;;
esac
